# Generated by Django 3.2.5 on 2021-08-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file',
        ),
        migrations.AddField(
            model_name='song',
            name='ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
